name = "www-hydrozidtr-com"
main = "src/index.js"
compatibility_date = "2026-03-09"

[assets]
directory = "."
binding = "ASSETS"

[vars]
BASE_URL = "https://www.hydrozidtr.com"

[[kv_namespaces]]
binding = "PAYMENT_KV"
id = "895fa32fe29d4157a77fbdc33a4d8b5a"
