name = "www-hydrozid-com-tr"
type = "javascript"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "PAYMENT_KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_KV_PREVIEW_ID"

[vars]
PRODUCT_PRICE_TRY = "149"
BASE_URL = "https://www.hydrozidtr.com"
PLATFORMODE_BASE = "https://app.halkode.com.tr/ccpayment"
MERCHANT_ID = "74096"

# Secrets (set via: wrangler pages secret put VARIABLE_NAME)
# APP_ID          = b84135b42f42ff90c1de8707eabb4fa0
# APP_SECRET      = 957bd1fe58958931b8e04e31e4a211ad
# MERCHANT_KEY    = $2y$10$mysuQEWP.9cRDRXPHGcjLO3SMQKECMRWHQEU3QYiZ1SsuXhUvuSy6
